"use client";
import { ChevronRight, Download, Radio, RefreshCw, ShieldCheck, UserCheck, UserX, Users, WifiOff } from "../components/Icons";
import { useHallzee } from "../HallzeeProvider";

const duration = (seconds: number) => `${Math.floor(seconds / 60)}m ${String(seconds % 60).padStart(2, "0")}s`;
const studentName = (name: string, id: string) => name.trim() || `Student ID #${id}`;

export default function DashboardPage() {
  const { terminalState, connectedTerminalName, isOccupied, activeTrip, lastSyncTime, trips, rosterFileName, findTerminals, syncNow, toggleOccupancy, exportCsv, setView } = useHallzee();
  const disconnected = terminalState === "disconnected" || terminalState === "recoverableError";
  const syncing = terminalState === "syncing";
  return <div className="space-y-6 pb-24">
    <section className="p-4 rounded-3xl bg-white/90 border border-sky-200 shadow-lg flex flex-wrap items-center justify-between gap-4">
      <div className="flex items-center gap-3.5"><div className={`h-11 w-11 rounded-2xl flex items-center justify-center text-white ${disconnected ? "bg-slate-400" : "bg-emerald-500"}`}>{disconnected ? <WifiOff/> : <Radio/>}</div><div><div className="flex items-center gap-2"><h2 className="font-extrabold">{disconnected ? "No Terminal Connected" : connectedTerminalName}</h2><span className={`text-xs rounded-full px-2.5 py-1 font-bold ${disconnected ? "bg-slate-200" : "bg-emerald-100 text-emerald-800"}`}>{disconnected ? "OFFLINE" : syncing ? "SYNCING" : "BLE CONNECTED"}</span></div><p className="text-sm text-slate-600 mt-1">{disconnected ? "Search for a nearby Hallzee kiosk." : <>Last successful sync: <strong>{lastSyncTime}</strong></>}</p></div></div>
      {disconnected ? <button onClick={findTerminals} className="rounded-2xl bg-sky-600 text-white px-5 py-2.5 font-bold">Find Terminal</button> : <div className="flex gap-2"><button onClick={syncNow} disabled={syncing} className="rounded-2xl bg-sky-600 text-white px-5 py-2.5 font-bold flex gap-2"><RefreshCw className={`w-4 ${syncing ? "animate-spin" : ""}`}/>{syncing ? "Syncing..." : "Sync Now"}</button><button onClick={() => setView("terminal")} className="rounded-2xl bg-white border border-sky-200 px-4 py-2.5 font-bold text-sky-900">Configure Node</button></div>}
    </section>

    <section className={`rounded-3xl p-5 min-h-40 flex items-center justify-between gap-5 border-2 shadow-lg ${disconnected ? "bg-white border-slate-200" : isOccupied ? "bg-amber-50 border-amber-300" : "bg-emerald-50 border-emerald-300"}`}>
      <div className="flex items-center gap-4 min-w-0"><div className={`h-16 w-16 rounded-2xl flex items-center justify-center text-white shrink-0 ${disconnected ? "bg-slate-400" : isOccupied ? "bg-amber-500" : "bg-emerald-500"}`}>{disconnected ? <WifiOff className="w-8"/> : isOccupied ? <UserX className="w-8"/> : <UserCheck className="w-8"/>}</div><div><span className={`inline-block rounded-full px-3 py-1 text-xs font-extrabold ${disconnected ? "bg-slate-200" : isOccupied ? "bg-amber-500 text-white" : "bg-emerald-500 text-white"}`}>{disconnected ? "TERMINAL OFFLINE" : isOccupied ? "PASS OCCUPIED (DEMO STATE)" : "PASS AVAILABLE (DEMO STATE)"}</span><h2 className="text-2xl font-black mt-2">{disconnected ? "Terminal Disconnected" : isOccupied ? `${studentName(activeTrip.studentName, activeTrip.studentId)} is Out of Class` : "Restroom is Currently Empty"}</h2><p className="text-sm text-slate-600 mt-1">{disconnected ? "Find and connect to the classroom kiosk." : isOccupied ? `Departed at ${activeTrip.departTime} for ${activeTrip.destination}.` : "The physical Hallzee terminal is ready for the next student."}</p></div></div>
      {!disconnected && <div className="w-72 bg-white border rounded-2xl p-4 flex items-center justify-between shadow"><div><span className="text-xs uppercase font-bold text-slate-500">{isOccupied ? "Trip Elapsed" : "Pass State"}</span><div className={`text-2xl font-black ${isOccupied ? "text-amber-600" : "text-emerald-700"}`}>{isOccupied ? duration(activeTrip.elapsedSeconds) : "Ready"}</div><span className="text-sm text-slate-500">{isOccupied ? `ID: #${activeTrip.studentId}` : "Door kiosk live"}</span></div><button onClick={toggleOccupancy} className="rounded-2xl bg-slate-900 text-white px-4 py-2.5 font-bold">{isOccupied ? "Check In" : "Simulate Tap"}</button></div>}
    </section>

    <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
      <section className="xl:col-span-2 bg-white/90 border border-sky-200 rounded-3xl p-5 shadow-lg"><div className="flex flex-wrap justify-between gap-3 border-b border-sky-100 pb-3 mb-3"><div><h2 className="font-extrabold">Recent Hall Pass Activity</h2><p className="text-sm text-slate-500">Latest completed student trips</p></div><div className="flex gap-2"><button onClick={exportCsv} className="rounded-xl border border-sky-200 px-3 py-2 text-sm font-bold flex gap-1"><Download className="w-4"/>Export CSV</button><button onClick={() => setView("trips")} className="rounded-xl bg-sky-100 text-sky-900 px-3 py-2 text-sm font-bold flex gap-1">View All History<ChevronRight className="w-4"/></button></div></div><div className="space-y-2">{trips.slice(0,4).map((trip) => <div key={trip.id} className="flex items-center justify-between p-3 rounded-2xl border border-sky-100"><div><div className="font-bold">{studentName(trip.studentName, trip.studentId)}</div><div className="text-sm text-slate-500">#{trip.studentId} • {trip.departTime} → {trip.returnTime}</div></div><div className="text-right"><div className="font-bold">{duration(trip.durationSeconds)}</div><span className={`text-xs rounded-full px-2 py-1 font-bold ${trip.status === "OCCUPIED" ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-800"}`}>{trip.status === "OCCUPIED" ? "Out" : "Returned"}</span></div></div>)}</div></section>
      <section className="bg-white/90 border border-sky-200 rounded-3xl p-5 shadow-lg flex flex-col justify-between gap-4"><div><h2 className="font-extrabold flex items-center gap-2 border-b border-sky-100 pb-3"><ShieldCheck className="w-5 text-sky-600"/>Roster & Pass Policy</h2><div className="mt-3 p-4 rounded-2xl bg-sky-50 text-sm space-y-2"><div className="flex justify-between"><span>Pass Capacity:</span><strong>1 Student</strong></div><div className="flex justify-between"><span>Overdue Warning:</span><strong className="text-amber-600">8 minutes</strong></div><div className="flex justify-between"><span>Daily Max:</span><strong>3 trips</strong></div></div><div className="mt-3 p-4 rounded-2xl bg-sky-50"><span className="text-xs uppercase font-bold text-slate-500">Loaded Roster CSV</span><div className="font-mono text-sm font-bold truncate mt-1">{rosterFileName}</div></div></div><button onClick={() => setView("roster")} className="rounded-2xl bg-sky-600 text-white py-2.5 font-bold flex justify-center gap-2"><Users className="w-4"/>Manage Student Roster CSV</button></section>
    </div>
  </div>;
}
